In [95]:
import os
import pandas as pd
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix
from sklearn.tree import export_text
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score
from sklearn import tree

In [72]:
os.listdir()

['.ipynb_checkpoints',
 '.python-version',
 'diabetes_binary_5050split_health_indicators_BRFSS2015.csv',
 'heart.csv',
 'Untitled.ipynb',
 'venv']

In [73]:
df_heart_master = pd.read_csv('heart.csv')
df_diabetes_master = pd.read_csv('diabetes_binary_5050split_health_indicators_BRFSS2015.csv')

In [74]:
df_heart_master['HeartDisease'].value_counts()

HeartDisease
1    508
0    410
Name: count, dtype: int64

In [75]:
df_diabetes_master['Diabetes_binary'].value_counts()

Diabetes_binary
0.0    35346
1.0    35346
Name: count, dtype: int64

In [76]:
df_heart_master.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [77]:
df_diabetes_master.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

In [78]:
df_heart_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [79]:
df_diabetes_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70692 entries, 0 to 70691
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Diabetes_binary       70692 non-null  float64
 1   HighBP                70692 non-null  float64
 2   HighChol              70692 non-null  float64
 3   CholCheck             70692 non-null  float64
 4   BMI                   70692 non-null  float64
 5   Smoker                70692 non-null  float64
 6   Stroke                70692 non-null  float64
 7   HeartDiseaseorAttack  70692 non-null  float64
 8   PhysActivity          70692 non-null  float64
 9   Fruits                70692 non-null  float64
 10  Veggies               70692 non-null  float64
 11  HvyAlcoholConsump     70692 non-null  float64
 12  AnyHealthcare         70692 non-null  float64
 13  NoDocbcCost           70692 non-null  float64
 14  GenHlth               70692 non-null  float64
 15  MentHlth              70692 non-null  float64
 16  PhysHlth              70692 non-null  float64
 17  DiffWalk              70692 non-null  float64
 18  Sex                   70692 non-null  float64
 19  Age                   70692 non-null  float64
 20  Education             70692 non-null  float64
 21  Income                70692 non-null  float64
dtypes: float64(22)
memory usage: 11.9 MB

In [80]:
df_heart = pd.get_dummies(df_heart_master, columns=['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope'], drop_first=True)

In [81]:
df_heart.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,1,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,0,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,1,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,0,True,False,True,False,True,False,False,False,True

In [82]:
X_heart = df_heart.drop(columns=['HeartDisease'])
y_heart = df_heart['HeartDisease']
print(X_heart)
print(y_heart)

     Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  Sex_M  \
0     40        140          289          0    172      0.0   True
1     49        160          180          0    156      1.0  False
2     37        130          283          0     98      0.0   True
3     48        138          214          0    108      1.5  False
4     54        150          195          0    122      0.0   True
..   ...        ...          ...        ...    ...      ...    ...
913   45        110          264          0    132      1.2   True
914   68        144          193          1    141      3.4   True
915   57        130          131          0    115      1.2   True
916   57        130          236          0    174      0.0  False
917   38        138          175          0    173      0.0   True

     ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA  \
0                 True              False             False
1                False               True             False
2                 True              False             False
3                False              False             False
4                False               True             False
..                 ...                ...               ...
913              False              False              True
914              False              False             False
915              False              False             False
916               True              False             False
917              False               True             False

     RestingECG_Normal  RestingECG_ST  ExerciseAngina_Y  ST_Slope_Flat  \
0                 True          False             False          False
1                 True          False             False           True
2                False           True             False          False
3                 True          False              True           True
4                 True          False             False          False
..                 ...            ...               ...            ...
913               True          False             False           True
914               True          False             False           True
915               True          False              True           True
916              False          False             False           True
917               True          False             False          False

     ST_Slope_Up
0           True
1          False
2           True
3          False
4           True
..           ...
913        False
914        False
915        False
916        False
917         True

[918 rows x 15 columns]
0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [83]:
X_diabetes = df_diabetes_master.drop(columns=['Diabetes_binary'])
y_diabetes = df_diabetes_master['Diabetes_binary']
print(X_diabetes)
print(y_diabetes)

       HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0         1.0       0.0        1.0  26.0     0.0     0.0
1         1.0       1.0        1.0  26.0     1.0     1.0
2         0.0       0.0        1.0  26.0     0.0     0.0
3         1.0       1.0        1.0  28.0     1.0     0.0
4         0.0       0.0        1.0  29.0     1.0     0.0
...       ...       ...        ...   ...     ...     ...
70687     0.0       1.0        1.0  37.0     0.0     0.0
70688     0.0       1.0        1.0  29.0     1.0     0.0
70689     1.0       1.0        1.0  25.0     0.0     0.0
70690     1.0       1.0        1.0  18.0     0.0     0.0
70691     1.0       1.0        1.0  25.0     0.0     0.0

       HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
0                       0.0           1.0     0.0      1.0  ...
1                       0.0           0.0     1.0      0.0  ...
2                       0.0           1.0     1.0      1.0  ...
3                       0.0           1.0     1.0      1.0  ...
4                       0.0           1.0     1.0      1.0  ...
...                     ...           ...     ...      ...  ...
70687                   0.0           0.0     0.0      1.0  ...
70688                   1.0           0.0     1.0      1.0  ...
70689                   1.0           0.0     1.0      0.0  ...
70690                   0.0           0.0     0.0      0.0  ...
70691                   1.0           1.0     1.0      0.0  ...

       AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  \
0                1.0          0.0      3.0       5.0      30.0       0.0  1.0
1                1.0          0.0      3.0       0.0       0.0       0.0  1.0
2                1.0          0.0      1.0       0.0      10.0       0.0  1.0
3                1.0          0.0      3.0       0.0       3.0       0.0  1.0
4                1.0          0.0      2.0       0.0       0.0       0.0  0.0
...              ...          ...      ...       ...       ...       ...  ...
70687            1.0          0.0      4.0       0.0       0.0       0.0  0.0
70688            1.0          0.0      2.0       0.0       0.0       1.0  1.0
70689            1.0          0.0      5.0      15.0       0.0       1.0  0.0
70690            1.0          0.0      4.0       0.0       0.0       1.0  0.0
70691            1.0          0.0      2.0       0.0       0.0       0.0  0.0

        Age  Education  Income
0       4.0        6.0     8.0
1      12.0        6.0     8.0
2      13.0        6.0     8.0
3      11.0        6.0     8.0
4       8.0        5.0     8.0
...     ...        ...     ...
70687   6.0        4.0     1.0
70688  10.0        3.0     6.0
70689  13.0        6.0     4.0
70690  11.0        2.0     4.0
70691   9.0        6.0     2.0

[70692 rows x 21 columns]
0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
70687    1.0
70688    1.0
70689    1.0
70690    1.0
70691    1.0
Name: Diabetes_binary, Length: 70692, dtype: float64

In [96]:
# training and evaluating on the heart dataset

X_train, X_test, y_train, y_test = train_test_split(X_heart, y_heart,random_state=0)
X_train_vals = X_train.values
X_test_vals = X_test.values
y_train_vals = y_train.values
y_test_vals = y_test.values


clf = tree.DecisionTreeClassifier(max_depth=3)
clf = clf.fit(X_train_vals,y_train_vals)

y_pred = clf.predict(X_test_vals)
print('confusion matrix')
print(confusion_matrix(y_test_vals, y_pred))
print('Accuracy score')
print(accuracy_score(y_test_vals,y_pred))
print('recall/sensitivity score')
print(recall_score(y_test_vals,y_pred))
# tree.plot_tree(clf)

confusion matrix
[[ 67  25]
 [ 12 126]]
Accuracy score
0.8391304347826087
recall/sensitivity score
0.9130434782608695

In [97]:
# training and evaluating on the heart dataset

X_train_diabetes, X_test_diabetes, y_train_diabetes, y_test_diabetes = train_test_split(X_diabetes, y_diabetes,random_state=0)
X_train_diabetes_vals = X_train_diabetes.values
X_test_diabetes_vals = X_test_diabetes.values
y_train_diabetes_vals = y_train_diabetes.values
y_test_diabetes_vals = y_test_diabetes.values


clf_diabetes = tree.DecisionTreeClassifier(max_depth=3)
clf_diabetes = clf_diabetes.fit(X_train_diabetes_vals, y_train_diabetes_vals)

y_pred_diabetes = clf_diabetes.predict(X_test_diabetes_vals)
print('confusion matrix')
print(confusion_matrix(y_test_diabetes_vals, y_pred_diabetes))
print('Accuracy score')
print(accuracy_score(y_test_diabetes_vals, y_pred_diabetes))
print('recall/sensitivity score')
print(recall_score(y_test_diabetes_vals, y_pred_diabetes))
#tree.plot_tree(clf)
#r = export_text(clf_diabetes, feature_names=list(X_diabetes.columns))
#print(r)

confusion matrix
[[5091 3598]
 [1440 7544]]
Accuracy score
0.7149323827307191
recall/sensitivity score
0.8397150489759573